name: CI

on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    - dev/**
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'GlibcOffsetGen.sln'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get 32 bit deps
      run: |
        sudo apt-get install gcc-multilib
        sudo apt-get install g++-multilib

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Run
      run: dotnet run --project ./GlibcOffsetGen/GlibcOffsetGen.csproj

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION }} /p:Configuration=${{ env.BUILD_CONFIG }} /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura -l "console;verbosity=detailed"
    
    - name: Publish artefacts
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output/**
